import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'services/auction_service.dart';
import 'models/auction_model.dart';

class CreateAuctionScreen extends StatefulWidget {
  const CreateAuctionScreen({super.key});

  @override
  State<CreateAuctionScreen> createState() => _CreateAuctionScreenState();
}

class _CreateAuctionScreenState extends State<CreateAuctionScreen> {
  final TextEditingController _cropNameController = TextEditingController();
  final TextEditingController _quantityController = TextEditingController();
  final TextEditingController _minPriceController = TextEditingController();
  final TextEditingController _locationController = TextEditingController(text: 'Green Valley Farms, Punjab');

  String _quality = 'A Grade';
  String _duration = '48h';
  
  File? _imageFile;
  bool _isLoading = false;
  final AuctionService _auctionService = AuctionService();

  @override
  void dispose() {
    _cropNameController.dispose();
    _quantityController.dispose();
    _minPriceController.dispose();
    _locationController.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    final picker = ImagePicker();
    final pickedFile = await picker.pickImage(source: ImageSource.gallery);
    if (pickedFile != null) {
      setState(() {
        _imageFile = File(pickedFile.path);
      });
    }
  }

  Future<void> _submitAuction() async {
    if (_imageFile == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please upload an image')));
      return;
    }
    if (_cropNameController.text.isEmpty || _quantityController.text.isEmpty || _minPriceController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please fill all fields')));
      return;
    }

    setState(() => _isLoading = true);
    try {
      final farmerId = FirebaseAuth.instance.currentUser?.uid ?? '';
      int hours = int.parse(_duration.replaceAll('h', ''));
      final startTime = DateTime.now();
      final endTime = startTime.add(Duration(hours: hours));

      final auction = AuctionModel(
        id: '', // Generated by Firestore
        cropName: _cropNameController.text,
        imageUrl: '', // Will be updated by service
        quantity: _quantityController.text,
        minPrice: double.parse(_minPriceController.text),
        quality: _quality,
        duration: hours,
        startTime: startTime,
        endTime: endTime,
        locationName: _locationController.text,
        farmerId: farmerId,
        status: 'active',
        highestBid: double.parse(_minPriceController.text),
        totalBids: 0,
        createdAt: DateTime.now(),
      );

      await _auctionService.createAuction(auction: auction, imageFile: _imageFile!);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Auction started securely!')));
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF0FDF4), // background-light
      appBar: AppBar(
        backgroundColor: Colors.white.withValues(alpha: 0.8),
        elevation: 0,
        centerTitle: true,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Color(0xFF0F172A)),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          'Create New Auction',
          style: TextStyle(
            color: Color(0xFF0F172A),
            fontSize: 18,
            fontWeight: FontWeight.bold,
          ),
        ),
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(1),
          child: Container(
            color: const Color(0xFF15803D).withValues(alpha: 0.1),
            height: 1,
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          children: [
            _buildVisualSection(),
            const SizedBox(height: 16),
            _buildGeneralInfoSection(),
            const SizedBox(height: 16),
            _buildQualitySection(),
            const SizedBox(height: 16),
            _buildDurationSection(),
            const SizedBox(height: 16),
            _buildLocationSection(),
            const SizedBox(height: 32),
            _buildSubmitButton(context),
            const SizedBox(height: 32),
          ],
        ),
      ),
    );
  }

  Widget _buildSectionContainer({required String title, required Widget child}) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFF15803D).withValues(alpha: 0.05)),
        boxShadow: const [
          BoxShadow(
            color: Colors.black12,
            blurRadius: 4,
            offset: Offset(0, 1),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title.toUpperCase(),
            style: const TextStyle(
              fontSize: 12,
              fontWeight: FontWeight.bold,
              color: Color(0xFF15803D), // primary
              letterSpacing: 1,
            ),
          ),
          const SizedBox(height: 16),
          child,
        ],
      ),
    );
  }

  Widget _buildVisualSection() {
    return _buildSectionContainer(
      title: 'Visual Details',
      child: AspectRatio(
        aspectRatio: 16 / 9,
        child: GestureDetector(
          onTap: _pickImage,
          child: Container(
            decoration: BoxDecoration(
              color: const Color(0xFFECFDF5), // emerald-50
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: const Color(0xFF15803D).withValues(alpha: 0.3),
                width: 2,
                style: BorderStyle.solid,
              ),
              image: _imageFile != null
                  ? DecorationImage(
                      image: FileImage(_imageFile!),
                      fit: BoxFit.cover,
                    )
                  : const DecorationImage(
                      image: NetworkImage(
                        'https://images.unsplash.com/photo-1595841696677-6489ff3f8cd1?auto=format&fit=crop&q=80&w=800',
                      ),
                      fit: BoxFit.cover,
                    ),
            ),
            child: Center(
              child: Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.white.withValues(alpha: 0.9),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: const Color(0xFF15803D).withValues(alpha: 0.2)),
                  boxShadow: const [
                    BoxShadow(color: Colors.black12, blurRadius: 8),
                  ],
                ),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: const [
                    Icon(Icons.add_a_photo, color: Color(0xFF15803D), size: 32),
                    SizedBox(height: 4),
                    Text(
                      'Upload Crop Image',
                      style: TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                        color: Color(0xFF475569),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildGeneralInfoSection() {
    return _buildSectionContainer(
      title: 'Crop Information',
      child: Column(
        children: [
          _buildTextField(
            label: 'Crop Name',
            controller: _cropNameController,
            hint: 'e.g. Sona Masoori Paddy',
          ),
          const SizedBox(height: 16),
          Row(
            children: [
              Expanded(
                child: _buildTextField(
                  label: 'Quantity',
                  controller: _quantityController,
                  hint: '0.00',
                  keyboardType: TextInputType.number,
                  suffixText: 'TONS',
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: _buildTextField(
                  label: 'Min. Price',
                  controller: _minPriceController,
                  hint: '0.00',
                  keyboardType: TextInputType.number,
                  suffixText: '₹/KG',
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildTextField({
    required String label,
    required TextEditingController controller,
    String? hint,
    TextInputType keyboardType = TextInputType.text,
    String? suffixText,
    IconData? leftIcon,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        if (label.isNotEmpty)
          Padding(
            padding: const EdgeInsets.only(left: 4, bottom: 6),
            child: Text(
              label,
              style: const TextStyle(
                fontSize: 14,
                fontWeight: FontWeight.w500,
                color: Color(0xFF334155),
              ),
            ),
          ),
        TextField(
          controller: controller,
          keyboardType: keyboardType,
          decoration: InputDecoration(
            hintText: hint,
            hintStyle: TextStyle(color: Colors.grey.shade400),
            filled: true,
            fillColor: const Color(0xFFF8FAFC), // slate-50
            prefixIcon: leftIcon != null ? Icon(leftIcon, color: const Color(0xFF15803D)) : null,
            suffixIcon: suffixText != null
                ? Padding(
                    padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 16),
                    child: Text(
                      suffixText,
                      style: const TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                        color: Color(0xFF15803D),
                      ),
                    ),
                  )
                : null,
            contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: const BorderSide(color: Color(0xFFE2E8F0)), // slate-200
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: const BorderSide(color: Color(0xFFE2E8F0)),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: const BorderSide(color: Color(0xFF15803D), width: 2),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildQualitySection() {
    return _buildSectionContainer(
      title: 'Crop Quality',
      child: Wrap(
        spacing: 8,
        runSpacing: 8,
        children: [
          _buildPillButton('A Grade'),
          _buildPillButton('B Grade'),
          _buildPillButton('Organic'),
        ],
      ),
    );
  }

  Widget _buildPillButton(String text) {
    final isSelected = _quality == text;
    return InkWell(
      onTap: () {
        setState(() {
          _quality = text;
        });
      },
      borderRadius: BorderRadius.circular(24),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        decoration: BoxDecoration(
          color: isSelected ? const Color(0xFF15803D).withValues(alpha: 0.1) : Colors.transparent,
          borderRadius: BorderRadius.circular(24),
          border: Border.all(
            color: isSelected ? const Color(0xFF15803D) : const Color(0xFFE2E8F0),
            width: 2,
          ),
        ),
        child: Text(
          text,
          style: TextStyle(
            fontSize: 14,
            fontWeight: isSelected ? FontWeight.bold : FontWeight.w500,
            color: isSelected ? const Color(0xFF15803D) : const Color(0xFF475569),
          ),
        ),
      ),
    );
  }

  Widget _buildDurationSection() {
    return _buildSectionContainer(
      title: 'Auction Duration',
      child: Row(
        children: [
          Expanded(child: _buildDurationOption('24h', 'Express')),
          const SizedBox(width: 8),
          Expanded(child: _buildDurationOption('48h', 'Standard')),
          const SizedBox(width: 8),
          Expanded(child: _buildDurationOption('72h', 'Extended')),
        ],
      ),
    );
  }

  Widget _buildDurationOption(String hours, String subtitle) {
    final isSelected = _duration == hours;
    return GestureDetector(
      onTap: () {
        setState(() {
          _duration = hours;
        });
      },
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 12),
        decoration: BoxDecoration(
          color: isSelected ? const Color(0xFF15803D) : Colors.transparent,
          borderRadius: BorderRadius.circular(8),
          border: Border.all(
            color: isSelected ? const Color(0xFF15803D) : const Color(0xFFE2E8F0),
            width: 2,
          ),
        ),
        child: Column(
          children: [
            Text(
              hours,
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
                color: isSelected ? Colors.white : const Color(0xFF1E293B),
              ),
            ),
            const SizedBox(height: 4),
            Text(
              subtitle.toUpperCase(),
              style: TextStyle(
                fontSize: 10,
                fontWeight: FontWeight.bold,
                color: isSelected ? Colors.white.withValues(alpha: 0.8) : const Color(0xFF64748B),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildLocationSection() {
    return _buildSectionContainer(
      title: 'Pickup Logistics',
      child: Column(
        children: [
          _buildTextField(
            label: '', // No external label here
            controller: _locationController,
            leftIcon: Icons.location_on,
          ),
          const SizedBox(height: 16),
          Container(
            height: 128,
            width: double.infinity,
            decoration: BoxDecoration(
              color: const Color(0xFFD1FAE5),
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: const Color(0xFFE2E8F0)),
              image: const DecorationImage(
                image: NetworkImage(
                  'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&q=80&w=800',
                ),
                fit: BoxFit.cover,
                colorFilter: ColorFilter.mode(Colors.black26, BlendMode.darken),
              ),
            ),
            child: Center(
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                decoration: BoxDecoration(
                  color: Colors.white.withValues(alpha: 0.9),
                  borderRadius: BorderRadius.circular(24),
                  boxShadow: const [BoxShadow(color: Colors.black12, blurRadius: 4)],
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: const [
                    Icon(Icons.my_location, color: Color(0xFF15803D), size: 16),
                    SizedBox(width: 4),
                    Text(
                      'Select on Map',
                      style: TextStyle(
                        color: Color(0xFF15803D),
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSubmitButton(BuildContext context) {
    return Column(
      children: [
        ElevatedButton(
          onPressed: _isLoading ? null : _submitAuction,
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF15803D),
            foregroundColor: Colors.white,
            minimumSize: const Size(double.infinity, 56),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(16),
            ),
            elevation: 8,
            shadowColor: const Color(0xFF15803D).withValues(alpha: 0.5),
          ),
          child: _isLoading 
            ? const CircularProgressIndicator(color: Colors.white)
            : const Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.gavel),
                  SizedBox(width: 8),
                  Text(
                    'Start Auction',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                ],
              ),
        ),
        const SizedBox(height: 16),
        const Padding(
          padding: EdgeInsets.symmetric(horizontal: 24),
          child: Text(
            'By starting the auction, you agree to the Smart Crop Terms of Service and Quality Guidelines.',
            textAlign: TextAlign.center,
            style: TextStyle(
              fontSize: 12,
              color: Color(0xFF64748B),
            ),
          ),
        ),
      ],
    );
  }
}
